import Head from 'next/head';
import Image from 'next/image';
import profilePic1 from '../../public/images/profile/developer-pic-1.png';
import profilePic2 from '../../public/images/profile/developer-pic-2.png';
import Layout from '@/components/Layout';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireME from '@/components/HireME';
import LightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';
import TransitionEffect from '../components/TransitionEffect';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {
    const router = useRouter();
    const backTo = router.query.backTo;
    useEffect(() => {
        if (backTo) {
        }
    }, [backTo]);
    return (
        <>
            <Head>
                <title>Prashlons | Home Page</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <TransitionEffect />
            <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
                <Layout className="pt-0 md:pt-16 sm:pt-8">
                    <div className="flex items-center justify-between w-full lg:flex-col">
                        <div className="w-1/2 md:w-full">
                            <Image
                                src={backTo === 'about' ? profilePic1 : profilePic2}
                                alt="prashlons"
                                className="w-full h-auto lg:hidden md:inline-block sm:w-full xs:w-full"
                                priority
                                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                            ></Image>
                        </div>
                        <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
                            <AnimatedText
                                text="A Web Alchemist who love to Craft Digital Masterpieces with Code and Design."
                                className="!text-5xl !text-left mb-4 xl:!text-5xl lg:!text-center lg:!text-5xl md:!text-5xl sm:!text-3xl sm:mt-3"
                            />
                            <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                                As a full-stack alchemist, I transmute ideas into innovative web
                                applications. Dive into my latest projects, revealing the alchemy of
                                web development expertise.
                            </p>
                            <div className="flex items-center self-start mt-2 lg:self-center">
                                <Link
                                    href="Prashil.Lonakar_Resume_SDE.pdf"
                                    target={'_blank'}
                                    className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark hover:border-dark border-2 border-solid border-transparent  dark:text-dark dark:bg-light hover:dark:text-dark hover:dark:border-light hover:dark:bg-dark hover:dark:text-light md:p-2 md:px-4 md:text-base"
                                    download={true}
                                >
                                    Resume{' '}
                                    <LinkArrow
                                        height={'1.625rem'}
                                        width={'1.625rem'}
                                        className={'w-6 ml-1'}
                                    />
                                </Link>
                                <Link
                                    href="mailto:prashil.lonakar@gmail.com?subject=Refer%20from%20Portfolio&body=Hello,%20I%20would%20like%20to%20connect%20with%20you%20regarding%20your%20Job%20Application.%0D%0A%0D%0AThank%20you."
                                    target={'_blank'}
                                    className="flex items-center ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                                >
                                    Contact
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
                <HireME />
                <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
                    <Image src={LightBulb} alt="Codebuck" className="w-full h-auto"></Image>
                </div>
            </main>
        </>
    );
}
